config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV.fetch("SIDEKIQ_USERNAME") &&
      password == ENV.fetch("SIDEKIQ_PASSWORD")
  end if Rails.env.production?
  mount Sidekiq::Web, :at => "/sidekiq"

  devise_for :users, :controllers => {:registrations => "registrations"}

  root "welcome#index"
  get "/documentation" => "welcome#documentation"
  get "/privacy"       => "welcome#privacy"
  get "/terms"         => "welcome#terms"

  mount V1.new => "/api/v1"

  mount StripeEvent::Engine, :at => "/hooks/stripe"

  namespace :my do
    get "/dashboard" => "dashboard#index", :as => :dashboard

    resource :account, :only => %i[ edit update destroy ] do
      member { put :change_card }
    end
    resources :sites do
      member { post :regenerate }
    end
    resources :invoices, :only => %i[ index show ]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
# frozen_string_literal: true

class Invoice < ApplicationRecord
  belongs_to :user

  validates :stripe_invoice_id, :presence => true, :uniqueness => true
  validates :invoiced_at,       :presence => true

  scope :order_by_date, lambda { order :invoiced_at => :desc }

  def sent?
    sent_at.present?
  end

  def site
    line = data["lines"]["data"].first
    subscription_id = line["subscription"] || line["id"]

    @site ||= user.sites.find_by(:stripe_subscription_id => subscription_id)
  end
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  belongs_to :site

  validates :name, :presence => true
  validates :path, :presence => true, :uniqueness => {:scope => :site_id}

  ThinkingSphinx::Callbacks.append(self, :behaviours => [:real_time])

  scope :deactivated_long_ago, lambda {
    where "deactivated_at IS NOT NULL AND deactivated_at < ?", 1.day.ago
  }

  def self.find_by_path(path)
    find_by(:path => path) || new(:path => path)
  end

  def deactivated?
    deactivated_at.present?
  end
end

app/models/site.rb
# frozen_string_literal: true

class Site < ApplicationRecord
  belongs_to :user
  has_many :pages, :dependent => :destroy

  validates :name,
    :presence   => true,
    :uniqueness => true,
    :format     => {:with => /\A[a-z0-9\-_]+\z/}
  validates :key,
    :presence   => true,
    :uniqueness => true

  before_validation :set_key, :on => :create

  scope :order_by_name, lambda { order :name => :asc }

  def accessible?
    %w[active past_due].include?(status)
  end

  def reset_key!
    update! :key => SecureRandom.hex(16)
  end

  private

  def set_key
    self.key ||= SecureRandom.hex 16
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable, :confirmable

  has_many :sites,    :dependent => :destroy
  has_many :invoices, :dependent => :destroy

  validates :country, :presence => true

  after_update :update_stripe

  private

  def update_stripe
    return unless unconfirmed_email_previously_changed?(:to => nil)

    UpdateCustomerWorker.perform_async(id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery :with => :exception

  expose(:section) { "home" }

  before_action :configure_permitted_parameters, :if => :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    my_dashboard_path
  end

  def after_sign_up_path_for(_resource)
    my_dashboard_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, :keys => [:country]
  end
end

app/controllers/my/accounts_controller.rb
# frozen_string_literal: true

class My::AccountsController < My::ApplicationController
  def update
    current_user.attributes = user_params

    if current_user.save
      redirect_to my_dashboard_path, :notice => t(".success")
    else
      render "edit"
    end
  end

  def destroy
    DeleteAccountWorker.perform_async current_user.id

    sign_out :user

    redirect_to root_path, :notice => t(".success")
  end

  def change_card
    UpdateCardWorker.perform_async current_user.id, params[:stripeToken]

    redirect_to my_dashboard_path, :notice => t(".success")
  end

  private

  def user_params
    params.fetch(:user, {}).permit :email, :country, :password,
      :password_confirmation
  end
end

app/controllers/my/application_controller.rb
# frozen_string_literal: true

class My::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/my/dashboard_controller.rb
# frozen_string_literal: true

class My::DashboardController < My::ApplicationController
  expose(:section) { "dashboard" }
end

app/controllers/my/invoices_controller.rb
# frozen_string_literal: true

class My::InvoicesController < My::ApplicationController
  expose(:section)  { "invoices" }
  expose(:invoices) { current_user.invoices.order_by_date.page(page) }
  expose(:invoice)  { current_user.invoices.find params[:id] }

  def show
    respond_to do |format|
      format.html
      format.pdf do
        send_data pdf.render, :filename => "invoice_#{invoice.id}.pdf"
      end
    end
  end

  private

  def page
    params[:page] ? params[:page].to_i : 1
  end

  def pdf
    InvoiceAsPdf.new invoice
  end
end

app/controllers/my/sites_controller.rb
# frozen_string_literal: true

class My::SitesController < My::ApplicationController
  expose(:section) { "sites" }
  expose(:sites)   { current_user.sites.order_by_name }
  expose(:site)    { site_in_context }

  def create
    if site.save
      SubscribeSiteWorker.perform_async site.id, params[:stripe_token]

      redirect_to my_sites_path
    else
      render :new
    end
  end

  def update
    if site.update site_params
      redirect_to my_site_path(site), :notice => t(".success")
    else
      render :edit
    end
  end

  def destroy
    site.update! :status => "deleting"
    CancelSiteWorker.perform_async site.id

    redirect_to my_sites_path
  end

  def regenerate
    site.reset_key!

    redirect_to my_site_path(site), :notice => t(".success")
  end

  private

  def site_in_context
    if params[:id].present?
      current_user.sites.find params[:id]
    else
      current_user.sites.new site_params
    end
  end

  def site_params
    params.fetch(:site, {}).permit(:name)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  # rubocop:disable Rails/LexicallyScopedActionFilter
  before_action :confirm_human, :only => [:create]
  # rubocop:enable Rails/LexicallyScopedActionFilter

  private

  def confirm_human
    return unless params[:human_verification].downcase["drumknott"].nil?

    build_resource(sign_up_params)

    flash[:alert] = t("registrations.confirm_human.failure")
    render :new
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  SECTIONS = ["documentation"].freeze

  expose(:section) { (SECTIONS & [params[:action]]).first || "home" }
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def external_javascript_version
    Rails.public_path.join("VERSION").read.strip
  end

  def require_credit_card?(site)
    site.new_record? && current_user.stripe_customer_id.blank?
  end
end

app/helpers/card_helper.rb
# frozen_string_literal: true

module CardHelper
  def current_user_last4
    current_user.cache.fetch("card", {})["last4"]
  end
end

app/helpers/invoices_helper.rb
# frozen_string_literal: true

module InvoicesHelper
  def invoice_number(invoice)
    invoice.id.to_s.rjust 6, "0"
  end

  def line_class_for(lines, line)
    lines.last == line ? "item last" : "item"
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{"http-equiv" => "Content-type", :content => "text/html; charset=utf-8"}
    %title Drumknott
    = stylesheet_link_tag    'application', :media => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #paperclips
      %h1 Drumknott
    %nav
      %ul{:class => section}
        %li.home= link_to 'Home', root_path
        %li.documentation= link_to 'Documentation', documentation_path
        - if user_signed_in?
          %li.dashboard= link_to 'Dashboard', my_dashboard_path
          %li.sites= link_to 'Sites', my_sites_path
          %li.invoices= link_to 'Invoices', my_invoices_path
          %li= link_to 'Log out', destroy_user_session_path, :method => :delete
        - else
          %li= link_to 'Sign up', new_user_registration_path
          %li= link_to 'Log in', new_user_session_path

    %section
      %p.notice= notice
      %p.alert= alert

      = yield

    %footer
      %p Drumknott is copyright <a href="http://freelancing-gods.com">Pat Allan</a> in 2016, and is open-sourced on <a href="https://github.com/pat/drumknott-server">GitHub</a>.
      %p
        ! View the #{ link_to 'Terms of Service', terms_path } and #{ link_to 'Privacy Policy', privacy_path }. Questions and support can be directed to either #{ link_to 'email', 'mailto:hello@drumknottsearch.com' } or #{ link_to 'Twitter', 'https://twitter.com/drumknottsearch' }.

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-72216381-1', 'auto');
      ga('send', 'pageview');

app/views/my/accounts/_form.html.haml
= semantic_form_for current_user, :url => my_account_path do |form|
  = form.inputs do
    = form.input :email
    = form.input :country, as: :country, priority_countries: [], hint: 'Required to handle billing correctly.'
  = form.actions do
    = form.action :submit, :as => :button, :label => 'Update', :button_html => {:class => 'button primary'}

%h3 Change Password

= semantic_form_for current_user, :url => my_account_path do |form|
  = form.inputs do
    = form.input :password, :label => 'New Password'
    = form.input :password_confirmation
  = form.actions do
    = form.action :submit, :as => :button, :label => 'Change Password', :button_html => {:class => 'button primary'}

app/views/my/accounts/edit.html.haml
= render :partial => 'form'

app/views/my/dashboard/index.html.haml
%h2 Account Details

= render :partial => 'my/accounts/form'

%h2 Credit Card

- if current_user.cache['card']
  %p The card on file ends with #{current_user_last4}, and expires at #{current_user.cache['card']['exp_month']}/#{current_user.cache['card']['exp_year']}.
- else
  %p You currently have no credit card attached to your account. Please use the button below to add new card details.

= form_tag change_card_my_account_path, method: :put do |form|
  %script{'src'        => 'https://checkout.stripe.com/checkout.js',
    'class'            => 'stripe-button',
    'data-key'         => ENV['STRIPE_PUBLISHABLE_KEY'],
    'data-name'        => 'Drumknott',
    'data-label'       => 'Update Credit Card',
    'data-description' => 'Update your credit card details',
    'data-panel-label' => 'Update',
    'data-locale'      => 'auto',
    'data-currency'    => 'USD',
    'data-email'       => current_user.email}

%h2 Close Account

%p If you've decided you'd like to stop using Drumknott and want to cancel all subscriptions and delete all data, just click the button below.

= link_to my_account_path, :method => :delete do
  %button.button.primary{:type => 'button'} Close

app/views/my/invoices/index.html.haml
%h2 Invoices

- if invoices.any?
  %table
    %thead
      %tr
        %th Number
        %th Date
        %th Site
        %th Amount
        %th Status
    %tbody
      - invoices.each do |invoice|
        %tr
          %td= link_to invoice_number(invoice), my_invoice_path(invoice)
          %td= invoice.invoiced_at
          %td= link_to invoice.site.name, my_site_path(invoice.site)
          %td= number_to_currency(invoice.data['total'] / 100.0)
          %td= invoice.data['paid'] ? 'Paid' : 'Unpaid'

  = paginate invoices
- else
  %p You do not have any invoices at this point.

app/views/my/invoices/show.html.haml
%p= link_to 'Return to list of invoices', my_invoices_path
%p= link_to 'Download PDF', my_invoice_path(invoice, :format => :pdf), :target => '_blank'

.invoice-box
  %table{:cellpadding => 0, :cellspacing => 0}
    %tr.top
      %td{:colspan => 2}
        %table
          %tr
            %td.title
              %h2 Drumknott
            %td
              Invoice #:
              = invoice_number invoice
              %br/
              Created:
              = invoice.invoiced_at.to_formatted_s :date_only
              %br/
              For
              = invoice.user.email
              %br/
              Status:
              = invoice.data['paid'] ? 'Paid' : 'Due'

    %tr.information
      %td{:colspan => 2}
        %table
          %tr
            %td
              Invoice From:
              %br/
              = ENV['INVOICE_FROM'].gsub("\n", "<br />").html_safe

    %tr.heading
      %td Item
      %td Amount
    - invoice.data['lines']['data'].each do |line|
      %tr{:class => line_class_for(invoice.data['lines']['data'], line)}
        %td Monthly subscription for #{ invoice.site.name }
        %td= number_to_currency(line['amount'] / 100.0)

    %tr.subtotal.first
      %td
      %td Subtotal: #{ number_to_currency(invoice.data['subtotal'] / 100.0) }

    - if invoice.data['discount']
      %tr.subtotal
        %td
        %td Discount: #{ number_to_currency(invoice.data['discount']['coupon']['percent_off'].to_i * invoice.data['subtotal'] / 10000.0) }

    %tr.total
      %td
      %td Total: #{ number_to_currency(invoice.data['total'] / 100.0) }

    %tr.footer
      %td{:rowspan => 2}
        %p
          #{ENV['INVOICE_REFERENCE_LABEL']}: #{ENV['INVOICE_REFERENCE']}
          %br/
          All dollar values listed are in #{invoice.data['currency'].upcase}.
          %br/
          - if current_user.country == 'AU'
            Total amount listed includes 10% GST for Australian customers.
            %br/
          ! For questions, support and feedback, please email #{ link_to 'hello@drumknottsearch.com', 'mailto:hello@drumknottsearch.com' }.

app/views/my/sites/_form.html.haml
%script{:src => 'https://checkout.stripe.com/checkout.js'}
= semantic_form_for [:my, site], :html => {:id => 'site_form'} do |form|
  = form.inputs do
    = form.input :name, :hint => 'Names can only contain lowercase letters, numbers, dashes and underscores.'
    = hidden_field_tag :stripe_token
  = form.actions do
    = form.action :submit, :as => :button, :button_html => {:class => 'button primary', :id => 'submit_site'}
  - if require_credit_card?(site)
    :javascript
      var handler = StripeCheckout.configure({
        key:    '#{ENV['STRIPE_PUBLISHABLE_KEY']}',
        locale: 'auto',
        token:  function(token) {
          console.log(token);
          $('#stripe_token').val(token.id);
          $('#site_form').submit();
          setTimeout(function() { $('submit_site').disable() }, 100);
        }
      });

      $('#submit_site').on('click', function(e) {
        handler.open({
          name:        'Drumknott',
          description: 'Monthly subscription ($3.00)',
          amount:       300,
          panelLabel:   'Subscribe',
          currency:     'USD',
          email:        '#{current_user.email}'
        });
        e.preventDefault();
      });

      $(window).on('popstate', function() {
        handler.close();
      });

app/views/my/sites/edit.html.haml
%h2 Edit Site

= render 'form'

%p If you change your site's name, make sure you update any credentials on your Jekyll site, including references in your Javascript code that make calls to Drumknott's Search API.

app/views/my/sites/index.html.haml
%h2 Sites

- if sites.any?
  %table
    %thead
      %tr
        %th Name
        %th API Key
        %th Status
    %tbody
      - sites.each do |site|
        %tr
          %td= link_to site.name, my_site_path(site)
          %td= site.key
          %td
            = site.status
            - if site.status == 'pending'
              = link_to 'refresh', my_sites_path

%h3 Add New Site

%p Each site costs $3.00 USD per month.

- unless require_credit_card?(site)
  %p The credit card on file (ending in #{current_user_last4}) will be used for this subscription.

= render 'form'

app/views/my/sites/new.html.haml
%h2 Add New Site

%p Each site costs $3.00 USD per month.

- unless require_credit_card?(site)
  %p The credit card on file (ending in #{current_user_last4}) will be used for this subscription.

= render 'form'

app/views/my/sites/show.html.haml
%h2 Site #{site.name}

%p The API key for this site is <strong><code>#{site.key}</code></strong>.
%p
  ! Please do not share this key with anyone, it is your private authentication for updating your site's data. If you think your key has been compromised, you can #{ link_to 'generate a new key', regenerate_my_site_path(site), :method => :post }.

- if site.cache['current_period_end']
  %p The current billing cycle finishes at #{ Time.zone.at site.cache['current_period_end'] }, and you will be billed for the next month shortly after that.

- case site.status
- when 'pending'
  %h4 Status: Pending
  %p
    ! Payment is being processed for this site. Hang tight, and perhaps #{ link_to 'refresh', my_site_path(site) } in a minute?
- when 'failure'
  %h4 Status: Payments Failed
  %p Payments have failed to be collected for this site, and it is no longer active.
- when 'past_due'
  %h4 Status: Past Due
  %p
    ! A payment has failed to be collected for this site. If you need to update your credit card details, that can be done on #{ link_to 'the dashboard', my_dashboard_path }.

%h3 Update Site

= render :partial => 'form'

%p If you change your site's name, make sure you update any credentials on your Jekyll site, including references in your Javascript code that make calls to Drumknott's Search API.

- unless site.status == 'deleting'
  %h3 Remove Site

  = link_to 'Cancel and Delete', my_site_path(site), :method => :delete, :data => {:confirm => 'This will cancel your subscription and delete all site data. Are you sure?'}

app/views/welcome/documentation.html.haml
%h2 Documentation

%p There are two key parts to using Drumknott on your Jekyll site: adding the relevant Javascript and HTML to have a search form on your site, and uploading your page data to the Drumknott API to ensure your search has results to return.

%h3 The Javascript

%p No matter how you choose to use Drumknott, you'll want to have two Javascript files included wherever you want your search form. The first is perhaps something you're already using: <a href="http://jquery.com">jQuery</a>. The second is Drumknott's own Javascript file (required to allow cross-domain search requests to Drumknott's API).

%p You'll need to add jQuery to your site if you haven't already, and then add the following to your HTML - probably within your head tag.

.highlighter-rouge
  %pre.highlight
    %code.html
      :escaped
        <script type="text/javascript" src="/javascripts/jquery.js"></script>
        <script type="text/javascript" src="https://drumknottsearch.com/drumknott-#{external_javascript_version}.js"></script>

%h4 Adding a search form

%p If you don't even want to think about the HTML for the form, the fully embeddable version can be used via some Javascript from Drumknott. Please note that this has an additional dependency on <a href="https://medialize.github.io/URI.js/">URI.js</a> and, like jQuery, you'll need to add this to your site yourself.

.highlighter-rouge
  %pre.highlight
    %code.html
      :escaped
        <!-- Put this with your other script tags -->
        <script type="text/javascript" src="/javascripts/uri.js"></script>

        <!-- Within your body tag, wherever you want the form to appear. -->
        <script type="text/javascript">
          search = new Drumknott('my-site-name');
          search.embed();
        </script>

%p Of course, the provided HTML markup and CSS may not be what you want, and the next section covers the minimal Javascript required to connect everything up yourself.

%h4 Manually querying the API

%p If you'd rather create your own form/interface and then make requests to Drumknott's API to populate search results, you can do that using the following Javascript code:

.highlighter-rouge
  %pre.highlight
    %code.js
      :escaped
        drumknott = new Drumknott('my-site-name');
        drumknott.search({query: "keywords", page: 1}, function(data) {
          // loop through data.results - each has name and path values,
          // and display search results as you wish.
        });

%h3 Uploading page data

%p As well as having a form sending through search requests to the Drumknott API, you'll also need to send your page data through so Drumknott can return relevant results. This is done via the <a href="https://github.com/pat/drumknott"><code>drumknott</code></a> gem, which you can add to your Gemfile:

.highlighter-rouge
  %pre.highlight
    %code.ruby
      :escaped
        # Gemfile
        gem 'drumknott', '~> 0.2.0'

%p Once this is installed, you will have access to the <code>drumknott</code> CLI tool which allows both saving your credentials locally and uploading your page data:

.highlighter-rouge
  %pre.highlight
    %code.shell
      :escaped
        drumknott keys SITE_NAME SITE_KEY INCLUDE_PAGES
        drumknott refresh

%p
  ! The first two arguments for the <code>keys</code> command are your site's name (when you registered it here at #{ link_to 'drumknottsearch.com', my_sites_path }), and the generated API key. The third argument, <code>INCLUDE_PAGES</code>, should be either <code>yes</code> or <code>no</code> - it's a flag to indicate whether you want non-blog-post pages to be uploaded as well.

%p The <code>keys</code> command will save your credentials in a file named <code>.drumknott</code> file to your current directory. Do <em>not</em> commit this file to source control. If you'd rather not have those credentials saved, you can supply them when running the refresh command as environment variables:

.highlighter-rouge
  %pre.highlight
    %code.shell
      :escaped
        drumknott refresh DRUMKNOTT_NAME=SITE_NAME \
          DRUMKNOTT_KEY=SITE_KEY DRUMKNOTT_PAGES=no

%p And that's it: Drumknott will have stored your page details, and your search queries will now return results. Keep in mind you'll need to run this command every time your site's content is updated.

%h3#api API

%p If you want to use the API directly yourself, you're certainly welcome to. There are three endpoints to use:

%h4 Updating page details

%pre
  %code
    PUT https://drumknottsearch.com/api/v1/SITE_NAME/pages

%p You will need to send your site's API key through as the value of the <code>AUTHENTICATION</code> request header, and the <code>Content-Type</code> header should be <code>application/json</code>. The body parameters need to be a JSON object with a single attribute <code>page</code>, which in turn has a JSON object of three attributes:

%ul.list
  %li
    %code name
    The page's title.
  %li
    %code path
    The path (without domain) to the page.
  %li
    %code content
    The rendered content of the page.

%p This request needs to be made for every page in your site that you wish to be searchable.

%pre
  %code
    :escaped
      curl -X PUT \
        -H "AUTHENTICATION: SITE_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{"page":{"name":"Blog Post","path":"/2016/01/01/blog-post.html","content":"<h1>Blog Post</h1>"}}' \
        https://drumknottsearch.com/api/v1/SITE_NAME/pages

%h4 Clearing existing page details

%pre
  %code
    POST https://drumknottsearch.com/api/v1/SITE_NAME/pages/clear

%p If you wish to clear out your existing data before updating each page, you can do so with this endpoint. You will need to send your site's API key through as the value of the <code>AUTHENTICATION</code> request header. No body or other headers are required.

%pre
  %code
    :escaped
      curl -X POST \
        -H "AUTHENTICATION: SITE_API_KEY" \
        https://drumknottsearch.com/api/v1/SITE_NAME/pages/clear

%h4 Searching pages

%pre
  %code
    GET https://drumknottsearch.com/api/v1/SITE_NAME/pages

%p This unauthenticated request will return search results for the given query. The allowed parameters are:

%ul.list
  %li
    %code query
    The search query.
  %li
    %code page
    The paginated page of results (if not provided, defaults to 1).
  %li
    %code per_page
    The number of paginated results per page (if not provided, defaults to 20).

%p The result will be a JSON object with the following attributes:

%ul.list
  %li
    %code results
    an array of search results as JSON objects with name and path attributes.
  %li
    %code page
    The paginated page of results.
  %li
    %code per_page
    The number of paginated results per page.
  %li
    %code pages
    The total number of pages available for this query.
  %li
    %code total
    The total number of results available for this query.
  %li
    %code error
    An error message if your site is not active.

%pre
  %code
    curl https://drumknottsearch.com/api/v1/SITE_NAME/pages?query=pancakes&page=1

%h3 Credits

%p Drumknott was built because I wanted to have a decent search page for my Jekyll-powered <a href="http://freelancing-gods.com">blog</a>. The site design is built on top of the excellent work on that blog by <a href="http://www.yellowshoe.com.au">Mark Brown</a>, and is <a href="https://github.com/pat/drumknott-server">open-sourced</a> (so you can submit patches if you'd like).

%p Drumknott is named after Sir Terry Pratchett's character Rufus Drumknott in his series of Discworld novels. <a href="http://www.gnuterrypratchett.com">GNU Terry Pratchett</a>.

app/views/welcome/index.html.haml
%blockquote
  %p Drumknott is an excellent clerk, and cannot abide such malpractices as deliberate misfiling.
  %cite= link_to 'Rufus Drumknott, from L-Space', 'http://wiki.lspace.org/mediawiki/Rufus_Drumknott'

%p
  ! Drumknott provides hosted searching for your static Jekyll sites. All you need to do is connect things up via Javascript, and upload your page data to Drumknott's API. The #{ link_to 'documentation', documentation_path } covers both steps in detail.

%p Each site costs $3 USD per month (which is GST-inclusive for Australian customers). If you'd like to see it in action before you pay anything, kick the tires on my blog's <a href="http://freelancing-gods.com/search.html">search page</a>.

%p
  ! If you'd like to set up your Jekyll site to use Drumknott, #{ link_to 'create an account!', new_user_registration_path } &mdash; or #{ link_to 'sign in', new_user_session_path } if you already have an account.